# Generated by Django 3.0.5 on 2020-04-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('photo', models.CharField(default=None, max_length=255, null=True)),
                ('question', models.CharField(max_length=4095)),
                ('option1', models.CharField(max_length=1023, null=True)),
                ('option2', models.CharField(max_length=1023, null=True)),
                ('option3', models.CharField(max_length=1023, null=True)),
                ('option4', models.CharField(max_length=1023, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('is_played', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('tg_id', models.IntegerField()),
                ('step', models.IntegerField(default=0)),
                ('temp_data', models.CharField(max_length=4095, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('option', models.IntegerField()),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Quiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
