# Generated by Django 3.0.7 on 2020-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200501_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
