# Generated by Django 3.0.7 on 2020-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_quiz_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='scheduled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
