# Generated by Django 2.2 on 2020-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200611_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description2',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description3',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description4',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
